SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE FUNCTION [dbo].[AreejAllocation] 
(
	@PALLETNUM INT
	,@PALLETLENGHT INT
)
RETURNS 
@ALLOCATION TABLE 
(
	ZONE VARCHAR(1)
	,NUM INT
)
AS
BEGIN
	DECLARE @LT INT
	DECLARE @WLT INT
	DECLARE @ST INT
	DECLARE @WST INT

	SELECT	@LT = (@PALLETLENGHT*@PALLETNUM)/24000

	SELECT	@WLT = 24000 - CASE (@PALLETLENGHT*@PALLETNUM)%24000
								WHEN 0 THEN 24000
								ELSE (@PALLETLENGHT*@PALLETNUM)%24000
						   END	

	SELECT	@PALLETNUM -= 24000/@PALLETLENGHT*@LT

	SELECT	@ST = (@PALLETLENGHT*@PALLETNUM)/5000

	SELECT	@WST = 5000 - CASE (@PALLETLENGHT*@PALLETNUM)%5000
								WHEN 0 THEN 5000
								ELSE (@PALLETLENGHT*@PALLETNUM)%5000
						   END	

	IF @WST <> 0
	BEGIN
		IF @WST < @WLT SET @ST += 1
		ELSE
		BEGIN 
			SET @LT += 1
			SET @ST = 0
		END
	END
	
	INSERT INTO @ALLOCATION VALUES ('C',@LT)
	INSERT INTO @ALLOCATION VALUES ('A',@ST)

	RETURN 
END

GO
