SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [AwmConfig].[vDestinazioni]
AS
	SELECT	ID_PARTIZIONE,
			DESCRIZIONE
	FROM	dbo.Partizioni
	WHERE	ID_TIPO_PARTIZIONE IN ('US', 'PK')
		AND ID_PARTIZIONE NOT IN (3101, 3301, 3302)
GO
