SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [AwmConfig].[vDestinazioniSpecializzazione] AS
SELECT	ID_PARTIZIONE			Id_Partizione,
		DESCRIZIONE
FROM	Partizioni
WHERE	ID_TIPO_PARTIZIONE = 'SP'
	OR	ID_PARTIZIONE = 3501
GO
