SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [AwmConfig].[vBaieKittingDispSeparate]
AS 
SELECT	CONCAT(ID_PARTIZIONE, ';')	ID_PARTIZIONE,
		DESCRIZIONE
FROM	AwmConfig.vBaieKittingDisponibili
GO
