SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [AwmConfig].[vTipoOpzioniUscita] AS 
SELECT 1 AS Id_Opzione, 'SCARICA IN AREA A TERRA' AS Descrizione
UNION
SELECT 2, 'ELIMINA UDC'
UNION
SELECT 3, 'SPOSTA UDC A INGOMBRANTI'
GO
