SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [AwmConfig].[vRigheDdtDaSpecializzareQta] as
SELECT Id_Udc,Id_Testata, NUMERO_RIGA, CODICE_ARTICOLO, DESCRIZIONE_ARTICOLO, QUANTITA_RIMANENTE_DA_SPECIALIZZARE, UNITA_DI_MISURA FROM [AwmConfig].[vRigheDdtDaSpecializzare] WHERE QUANTITA_RIMANENTE_DA_SPECIALIZZARE > 0
GO
