SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREAte view [AwmConfig].[vTestataOrdini] 
AS SELECT toe.LOAD_ORDER_ID, toe.LOAD_ORDER_TYPE, toe.DT_RECEIVE_BLM as DATARICEZIONEINBLM, toe.SUPPLIER_CODE
FROM Custom.TestataOrdiniEntrata toe
GO
