SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [AwmConfig].[vTipoBolle]
AS
	SELECT	1					ID_TIPO,
			'BOLLA FITTIZIA'	TIPO_BOLLA
	UNION
	SELECT  3,
			'INSERISCI ARTICOLI MANUALMENTE'
	UNION
	SELECT  4,
			'RIENTRO DA AREA A TERRA'
	UNION
	SELECT  5,
			'RIENTRO DA INGOMBRANTE'
	
GO
