SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [AwmConfig].[vRigheOrdiniEntrata] AS
SELECT	Id_Testata,
		LOAD_LINE_ID					NUMERO_RIGA,
		ITEM_CODE						CODICE_ARTICOLO,
		QUANTITY						QUANTITA,
		PURCHASE_ORDER_ID				CODICE_ORDINE_ACQUISTO,
		FL_INDEX_ALIGN					FLAG_ALLINEAMENTO_INDICE,
		CAST(FL_QUALITY_CHECK AS BIT)	FLAG_CONTROLLO_QUALITA,
		COMM_PROD						COMMESSA_PRODUZIONE,
		roe.WBS_ELEM					PROGETTO_WBS,
		--COMM_SALE						COMMESSA_VENDITA,
		MANUFACTURER_ITEM				CODICE_ARTICOLO_COSTRUTTORE,
		ROE.CONTROL_LOT					CONTROL_LOT,
		--MANUFACTURER_NAME				NUMERO_COSTRUTTORE,
		tro.Descrizione		STATO_RIGA
FROM	Custom.RigheOrdiniEntrata				roe
JOIN	Custom.Tipo_Stato_Righe_OrdiniEntrata	tro
ON		roe.Stato = tro.Id_Stato_Riga
GO
