SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [AwmConfig].[vOpzioniSceltaMancanti] AS
SELECT	1	Id_opzione,
		'PRELIEVO ARTICOLO MANCANTE'	Descrizione
UNION
SELECT	2,
		'LASCIA UDC INVARIATA'
GO
