CREATE TABLE [dbo].[Componenti]
(
[ID_SOTTOAREA] [int] NOT NULL,
[ID_COMPONENTE] [int] NOT NULL,
[DESCRIZIONE] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[CODICE_ABBREVIATO] [varchar] (2) COLLATE Latin1_General_CI_AS NOT NULL,
[ID_TIPO_COMPONENTE] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[ID_PLC] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Componenti] ADD CONSTRAINT [PK_Componenti_1] PRIMARY KEY CLUSTERED ([ID_COMPONENTE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Componenti] ON [dbo].[Componenti] ([ID_SOTTOAREA], [CODICE_ABBREVIATO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Componenti] ADD CONSTRAINT [FK_Componenti_Plc] FOREIGN KEY ([ID_PLC]) REFERENCES [dbo].[Plc] ([Id_Plc])
GO
ALTER TABLE [dbo].[Componenti] ADD CONSTRAINT [FK_Componenti_SottoAree] FOREIGN KEY ([ID_SOTTOAREA]) REFERENCES [dbo].[SottoAree] ([ID_SOTTOAREA])
GO
ALTER TABLE [dbo].[Componenti] ADD CONSTRAINT [FK_Componenti_Tipo_Componenti] FOREIGN KEY ([ID_TIPO_COMPONENTE]) REFERENCES [dbo].[Tipo_Componenti] ([ID_TIPO_COMPONENTE])
GO
